import React, { useEffect, useMemo, useRef, useState } from 'react'
import {
  Home, ClipboardList, TimerReset, Package, BarChart3, ChevronLeft, ChevronRight,
  Plus, Minus, Settings as SettingsIcon, History, Trophy, Flower2, Pause, Play,
  Square, Droplets, Milk, Sparkles, X, Download, Trash2, RotateCcw, Check, Share2
} from 'lucide-react'

const STORAGE_KEY = 'milkyMama.v1'
const defaultData = {
  sessions: [], stash: [],
  settings: { dailyGoal: 24, unit: 'oz', haptics: true, sounds: true, reduceMotion: false },
  gameScores: { dropPop: 0, stashStack: 0, mamaMatch: 0 },
}
const NAV = [
  ['home','Home',Home], ['log','Log',ClipboardList], ['pump','Pump Room',TimerReset],
  ['stash','Stash',Package], ['progress','Progress',BarChart3],
]
const uid = () => `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`
const sameDay = (a,b=new Date()) => new Date(a).toDateString() === new Date(b).toDateString()
const fmtDate = iso => new Date(iso).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})
const fmtTime = iso => new Date(iso).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})
const fmtDuration = s => `${Math.floor((s||0)/60)}m`
const clamp=(n,a,b)=>Math.min(Math.max(n,a),b)

function loadData(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY));return p?{...defaultData,...p,settings:{...defaultData.settings,...p.settings}}:defaultData}catch{return defaultData}}

export default function App(){
  const [screen,setScreen]=useState('home')
  const [data,setData]=useState(loadData)
  const [installPrompt,setInstallPrompt]=useState(null)
  useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(data)),[data])
  useEffect(()=>{const h=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',h);return()=>window.removeEventListener('beforeinstallprompt',h)},[])
  const go=s=>{window.scrollTo({top:0,behavior:data.settings.reduceMotion?'auto':'smooth'});setScreen(s)}
  const saveSession=s=>{setData(d=>({...d,sessions:[s,...d.sessions]}));go('home')}
  const common={data,setData,go,saveSession,installPrompt,
    addStash:item=>setData(d=>({...d,stash:[item,...d.stash]})),
    removeStash:id=>setData(d=>({...d,stash:d.stash.filter(x=>x.id!==id)})),
    updateSettings:p=>setData(d=>({...d,settings:{...d.settings,...p}})),
    setGameScore:(name,score)=>setData(d=>({...d,gameScores:{...d.gameScores,[name]:name==='mamaMatch'&&d.gameScores[name]?Math.min(d.gameScores[name],score):Math.max(d.gameScores[name]||0,score)}})),
  }
  const main=NAV.some(([id])=>id===screen)
  return <div className="app-shell"><main className="phone-stage">
    {screen==='home'&&<HomeScreen {...common}/>} {screen==='log'&&<LogScreen {...common}/>} {screen==='pump'&&<PumpScreen {...common}/>} {screen==='stash'&&<StashScreen {...common}/>} {screen==='progress'&&<ProgressScreen {...common}/>} {screen==='history'&&<HistoryScreen {...common}/>} {screen==='achievements'&&<AchievementsScreen {...common}/>} {screen==='garden'&&<GardenScreen {...common}/>} {screen==='drop-pop'&&<DropPopScreen {...common}/>} {screen==='stash-stack'&&<StashStackScreen {...common}/>} {screen==='mama-match'&&<MamaMatchScreen {...common}/>} {screen==='settings'&&<SettingsScreen {...common}/>} 
  </main>{main&&<BottomNav current={screen} go={go}/>}</div>
}

function BottomNav({current,go}){return <nav className="bottom-nav">{NAV.map(([id,label,Icon])=><button key={id} className={current===id?'active':''} onClick={()=>go(id)}><Icon size={19}/><span>{label}</span></button>)}</nav>}
function ScreenHeader({title,go,action,night=false}){return <header className={`screen-header ${night?'night':''}`}><button className="icon-button" onClick={()=>go('home')}><ChevronLeft size={22}/></button><h1>{title}</h1>{action||<span/>}</header>}
function Stat({label,value,small=false}){return <div className="stat-card"><span>{label}</span><strong className={small?'small':''}>{value}</strong></div>}
function Segmented({value,onChange,options}){return <div className="segmented">{options.map(([id,label])=><button key={id} className={value===id?'active':''} onClick={()=>onChange(id)}>{label}</button>)}</div>}
function Stepper({value,setValue,step=.5,min=0,suffix=''}){return <div className="stepper"><button onClick={()=>setValue(Math.max(min,Number(value)-step))}><Minus size={14}/></button><strong>{Number(value).toFixed(step<1?1:0)} <small>{suffix}</small></strong><button onClick={()=>setValue(Number(value)+step)}><Plus size={14}/></button></div>}
function FormRow({label,children}){return <div className="form-row"><span>{label}</span><div className="form-row-control">{children}</div></div>}
function Empty({icon,title,text}){return <div className="empty-card">{icon}<div><strong>{title}</strong><p>{text}</p></div></div>}
function Modal({title,onClose,children}){return <div className="modal-backdrop" onClick={onClose}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X size={17}/></button></div>{children}</div></div>}

function HomeScreen({data,go}){
  const hour=new Date().getHours(); const greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening'
  const today=data.sessions.filter(s=>sameDay(s.startedAt)); const ounces=today.reduce((a,s)=>a+Number(s.ounces||0),0); const goal=Number(data.settings.dailyGoal||24); const pct=clamp(Math.round(ounces/goal*100),0,100)
  const fridge=sumLocation(data.stash,'Fridge'), freezer=sumLocation(data.stash,'Freezer'), latest=data.sessions[0]
  return <div className="screen light home-screen"><div className="home-topbar"><div><h1>{greeting}, Mama! <span>{hour<18?'☀️':'🌙'}</span></h1><p>You’re doing amazing today.</p></div><button className="avatar-button" onClick={()=>go('settings')}><SettingsIcon size={18}/></button></div>
    <div className="progress-orbit" style={{'--progress':`${pct*3.6}deg`}}><div className="orbit-inner"><strong>{ounces.toFixed(1)}</strong><span>of {goal} oz</span><b>{pct}%</b></div></div>
    <div className="stat-grid three"><Stat label="Sessions" value={today.length}/><Stat label="Streak" value={calcStreak(data.sessions)}/><Stat label="Last Pump" value={latest?relativeTime(new Date(latest.startedAt)):'—'} small/></div>
    <div className="stash-preview-grid"><button className="stash-preview fridge" onClick={()=>go('stash')}><span>Fridge</span><strong>{fridge.toFixed(1)} oz</strong></button><button className="stash-preview freezer" onClick={()=>go('stash')}><span>Freezer</span><strong>{freezer.toFixed(1)} oz</strong></button></div>
    <button className="primary-cta" onClick={()=>go('pump')}><Milk size={19}/> Start Pumping</button><button className="secondary-cta" onClick={()=>go('log')}>Log Session</button>
    {data.sessions.length===0&&<div className="empty-card compact"><Droplets size={22}/><div><strong>Your first drop starts here</strong><p>Start a pumping timer or log a session to bring your dashboard to life.</p></div></div>}
    <section className="home-links"><button onClick={()=>go('garden')}><span className="link-bubble garden"><Flower2/></span><span><strong>Milky Garden</strong><small>Grow with every session</small></span><ChevronRight/></button><button onClick={()=>go('achievements')}><span className="link-bubble achievement"><Trophy/></span><span><strong>Achievements</strong><small>Celebrate your wins</small></span><ChevronRight/></button><button onClick={()=>go('history')}><span className="link-bubble history"><History/></span><span><strong>Session History</strong><small>See your full timeline</small></span><ChevronRight/></button></section>
  </div>
}

function LogScreen({data,go,saveSession}){
  const now=new Date(); const [mode,setMode]=useState('simple'),[unit,setUnit]=useState(data.settings.unit||'oz'),[date,setDate]=useState(now.toISOString().slice(0,10)),[time,setTime]=useState(now.toTimeString().slice(0,5)),[total,setTotal]=useState(0),[duration,setDuration]=useState(1200),[left,setLeft]=useState(0),[right,setRight]=useState(0),[tag,setTag]=useState('Home'),[notes,setNotes]=useState('')
  useEffect(()=>{if(mode==='advanced')setTotal(Number(left)+Number(right))},[mode,left,right])
  const save=()=>{const oz=unit==='mL'?total/29.5735:total;saveSession({id:uid(),startedAt:new Date(`${date}T${time}`).toISOString(),ounces:Number(oz.toFixed(2)),durationSec:duration,leftOz:mode==='advanced'?left:null,rightOz:mode==='advanced'?right:null,tag,notes})}
  return <div className="screen light"><ScreenHeader title="Log Session" go={go} action={<button className="text-action" onClick={save}>Save</button>}/><Segmented value={mode} onChange={setMode} options={[['simple','Simple'],['advanced','Advanced']]}/><div className="form-list"><FormRow label="Date"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></FormRow><FormRow label="Time"><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></FormRow>{mode==='simple'&&<FormRow label="Total Ounces"><Stepper value={total} setValue={setTotal} suffix={unit}/><div className="unit-toggle"><button className={unit==='oz'?'active':''} onClick={()=>setUnit('oz')}>oz</button><button className={unit==='mL'?'active':''} onClick={()=>setUnit('mL')}>mL</button></div></FormRow>}<FormRow label="Duration"><div className="stepper"><button onClick={()=>setDuration(Math.max(60,duration-60))}><Minus size={14}/></button><strong>{String(Math.floor(duration/60)).padStart(2,'0')}:00</strong><button onClick={()=>setDuration(duration+60)}><Plus size={14}/></button></div></FormRow></div>
    {mode==='advanced'&&<section className="form-section"><p className="eyebrow">Advanced Logging</p><FormRow label="Left Ounces"><Stepper value={left} setValue={setLeft} suffix="oz"/></FormRow><FormRow label="Right Ounces"><Stepper value={right} setValue={setRight} suffix="oz"/></FormRow><div className="calculated-total">Total = Left + Right = <strong>{(Number(left)+Number(right)).toFixed(1)} oz</strong> <Check size={14}/></div></section>}
    <div className="form-list second"><FormRow label="Tag"><select value={tag} onChange={e=>setTag(e.target.value)}><option>Home</option><option>Work</option><option>Night</option><option>Power Pump</option></select></FormRow><div className="notes-block"><label>Notes</label><textarea placeholder="How was this session?" value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><button className="primary-cta sticky-save" onClick={save}>Save Session</button></div>
}

function PumpScreen({data,go,saveSession}){
  const [elapsed,setElapsed]=useState(0),[running,setRunning]=useState(true),[finishMode,setFinishMode]=useState(false),[ounces,setOunces]=useState(0); const started=useRef(new Date())
  useEffect(()=>{if(!running)return;const t=setInterval(()=>setElapsed(s=>s+1),1000);return()=>clearInterval(t)},[running])
  const finish=()=>{if(!finishMode){setRunning(false);setFinishMode(true);return}saveSession({id:uid(),startedAt:started.current.toISOString(),ounces,durationSec:elapsed,leftOz:null,rightOz:null,tag:'Pump Room',notes:''})}
  return <div className="screen night pump-screen"><ScreenHeader title="Pumping Session" go={go} night action={<Sparkles size={16}/>}/><div className="stars">✦ · ✧ · ✦ · ✧ · ✦</div><div className="timer-display">{toClock(elapsed)}<span>Elapsed</span></div><div className="pump-actions"><button className="night-secondary" onClick={()=>setRunning(x=>!x)}>{running?<Pause/>:<Play/>}{running?'Pause':'Resume'}</button><button className="pink-button" onClick={finish}><Square size={16}/>{finishMode?'Save':'Finish'}</button></div>
    {finishMode&&<div className="finish-card"><label>How much did you pump?</label><Stepper value={ounces} setValue={setOunces} suffix="oz"/><button className="pink-button wide" onClick={finish}>Save Session</button></div>}
    <section className="quick-games"><h2>Quick Games</h2><p>Play a game while you pump!</p><div className="game-cards"><GameCard icon="💧" title="Drop Pop" meta={`High Score ${data.gameScores.dropPop||0}`} onClick={()=>go('drop-pop')}/><GameCard icon="🍼" title="Stash Stack" meta={`Best Stack ${data.gameScores.stashStack||0}`} onClick={()=>go('stash-stack')}/><GameCard icon="💗" title="Mama Match" meta={`Best ${data.gameScores.mamaMatch?`${data.gameScores.mamaMatch}s`:'—'}`} onClick={()=>go('mama-match')}/></div></section><div className="session-start-row"><span>Session Started</span><strong>{fmtTime(started.current)}</strong></div><button className="cancel-session" onClick={()=>go('home')}>Cancel Session</button></div>
}
function GameCard({icon,title,meta,onClick}){return <button className="game-card" onClick={onClick}><span className="game-icon">{icon}</span><strong>{title}</strong><small>{meta}</small></button>}

function StashScreen({data,go,addStash,removeStash}){
  const [filter,setFilter]=useState('All'),[open,setOpen]=useState(false),[ounces,setOunces]=useState(4),[location,setLocation]=useState('Fridge'); const list=filter==='All'?data.stash:data.stash.filter(x=>x.location===filter); const total=data.stash.reduce((a,b)=>a+Number(b.ounces),0)
  const add=()=>{addStash({id:uid(),ounces:Number(ounces),location,storedAt:new Date().toISOString()});setOpen(false)}
  return <div className="screen light"><ScreenHeader title="Stash" go={go} action={<button className="round-add" onClick={()=>setOpen(true)}><Plus size={17}/></button>}/><Segmented value={filter} onChange={setFilter} options={[['All','All'],['Fridge','Fridge'],['Freezer','Freezer'],['Room','Room']]}/><div className="stash-summary"><div><span>Total Stored</span><strong>{total.toFixed(1)} <small>oz</small></strong></div><div><span>Containers</span><strong>{data.stash.length}</strong></div></div><div className="stash-location-grid"><div className="mint-card"><span>Fridge</span><strong>{sumLocation(data.stash,'Fridge').toFixed(1)} oz</strong></div><div className="blue-card"><span>Freezer</span><strong>{sumLocation(data.stash,'Freezer').toFixed(1)} oz</strong></div></div><h2 className="section-title">Recent Containers</h2>{list.length===0?<Empty icon={<Milk/>} title="No milk stored yet" text="Add a container and choose where it’s stored."/>:<div className="container-list">{list.map(i=><div className="container-row" key={i.id}><span className={`bottle-dot ${i.location.toLowerCase()}`}><Milk size={17}/></span><span className="container-copy"><strong>Breast Milk</strong><small>{i.location} • {fmtDate(i.storedAt)}</small></span><strong>{Number(i.ounces).toFixed(1)} oz</strong><button className="tiny-delete" onClick={()=>removeStash(i.id)}><X size={14}/></button></div>)}</div>}{open&&<Modal title="Add Milk" onClose={()=>setOpen(false)}><label>Amount</label><Stepper value={ounces} setValue={setOunces} suffix="oz"/><label>Store in</label><select value={location} onChange={e=>setLocation(e.target.value)}><option>Fridge</option><option>Freezer</option><option>Room</option></select><button className="primary-cta" onClick={add}>Add to Stash</button></Modal>}</div>
}

function ProgressScreen({data,go}){
  const [range,setRange]=useState('7'); const days=range==='today'?1:range==='7'?7:30; const scoped=data.sessions.filter(s=>Date.now()-new Date(s.startedAt).getTime()<=days*86400000); const total=scoped.reduce((a,b)=>a+Number(b.ounces),0),avg=scoped.length?total/scoped.length:0,avgDur=scoped.length?scoped.reduce((a,b)=>a+(b.durationSec||0),0)/scoped.length:0; const chart=useMemo(()=>dailyBuckets(data.sessions,Math.min(days,7)),[data.sessions,days]); const achievements=getAchievements(data); const max=Math.max(...chart.map(x=>x.value),1)
  return <div className="screen light"><ScreenHeader title="Progress" go={go} action={<button className="icon-button" onClick={()=>go('settings')}><SettingsIcon size={18}/></button>}/><Segmented value={range} onChange={setRange} options={[['today','Today'],['7','7 Days'],['30','30 Days']]}/><div className="progress-stats"><Stat label="Total Ounces" value={`${total.toFixed(1)} oz`}/><Stat label="Sessions" value={scoped.length}/><Stat label="Average" value={`${avg.toFixed(1)} oz`}/></div><div className="avg-duration"><span>Avg Duration</span><strong>{fmtDuration(avgDur)}</strong></div><section className="chart-card"><h2>Ounces Per Day</h2><div className="bar-chart">{chart.map((d,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:`${Math.max(8,d.value/max*120)}px`}}/><small>{d.label}</small></div>)}</div></section><section className="achievement-preview"><div className="section-heading"><h2>Achievements</h2><button onClick={()=>go('achievements')}>View All</button></div><div className="achievement-badges">{achievements.slice(0,3).map(a=><div key={a.id}><span className={`badge ${a.unlocked?'unlocked':''}`}>{a.icon}</span><small>{a.title}</small></div>)}</div></section></div>
}

function GardenScreen({data,go}){const xp=data.sessions.length*12+Math.round(data.sessions.reduce((a,b)=>a+Number(b.ounces),0)),level=Math.max(1,Math.floor(xp/60)+1),inLevel=xp%60,plants=Math.min(6,Math.max(1,Math.ceil(data.sessions.length/3)));return <div className="screen garden-screen"><ScreenHeader title="Milky Garden" go={go}/><p className="garden-subtitle">Keep going, your garden is growing!</p><div className="garden-sky"><div className="string-lights">✦ ✧ ✦ ✧ ✦ ✧ ✦</div><span className="butterfly">🦋</span><div className="garden-plants">{Array.from({length:plants}).map((_,i)=><span key={i} className={`plant p${i}`}>{['🌷','🌼','🌸','🌻','🪻','🌺'][i]}</span>)}</div><div className="garden-ground">🌿 · 🌱 · 🌿 · 🌱 · 🌿</div></div><div className="garden-progress-card"><strong>Garden Progress</strong><div className="garden-progress-meta"><span>Level {level}</span><span>{inLevel} / 60 XP</span></div><div className="xp-track"><div style={{width:`${inLevel/60*100}%`}}/></div></div></div>}

function AchievementsScreen({data,go}){const a=getAchievements(data),unlocked=a.filter(x=>x.unlocked);return <div className="screen light"><ScreenHeader title="Achievements" go={go}/><p className="center-meta">{unlocked.length} / {a.length} Unlocked</p>{unlocked.length>0&&<><h2 className="section-title">Recently Unlocked</h2><div className="achievement-list">{unlocked.slice(0,2).map(x=><AchievementRow key={x.id} a={x}/>)}</div></>}<h2 className="section-title">All Achievements</h2><div className="achievement-list">{a.map(x=><AchievementRow key={x.id} a={x}/>)}</div></div>}
function AchievementRow({a}){return <div className={`achievement-row ${a.unlocked?'unlocked':''}`}><span className="achievement-icon">{a.icon}</span><span><strong>{a.title}</strong><small>{a.desc}</small></span>{a.unlocked?<span className="check-pill"><Check/></span>:<span className="achievement-progress">{a.progress}</span>}</div>}

function HistoryScreen({data,go}){const grouped=groupSessions(data.sessions);return <div className="screen light"><ScreenHeader title="History" go={go}/>{data.sessions.length===0?<Empty icon={<History/>} title="No sessions yet" text="Your pumping history will appear here."/>:Object.entries(grouped).map(([date,sessions])=><section className="history-day" key={date}><h2>{date}</h2>{sessions.map(s=><div className="history-row" key={s.id}><span><strong>{fmtTime(s.startedAt)}</strong><small>{fmtDuration(s.durationSec)}</small></span><strong>{Number(s.ounces).toFixed(1)} oz</strong><span className="history-sides">{s.leftOz!=null?<><small>L {Number(s.leftOz).toFixed(1)}</small><small>R {Number(s.rightOz).toFixed(1)}</small></>:<small>{s.tag}</small>}</span></div>)}</section>)}</div>}

function DropPopScreen({data,go,setGameScore}){const [score,setScore]=useState(0),[time,setTime]=useState(30),[paused,setPaused]=useState(false),[drops,setDrops]=useState(()=>newDrops());useEffect(()=>{if(paused||time<=0)return;const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[paused,time]);useEffect(()=>{if(time===0)setGameScore('dropPop',score)},[time,score]);const pop=id=>{if(time<=0||paused)return;setScore(s=>s+30);setDrops(ds=>ds.map(d=>d.id===id?randomDrop(id):d));if(data.settings.haptics&&navigator.vibrate)navigator.vibrate(18)};return <div className="screen night game-screen"><ScreenHeader title="Drop Pop" go={()=>go('pump')} night action={<span className="coin">● {data.gameScores.dropPop||0}</span>}/><div className="game-hud"><span>{time} sec</span><strong>{score}<small>x{Math.max(1,Math.floor(score/90)+1)} Combo</small></strong><button className="round-night" onClick={()=>setPaused(x=>!x)}>{paused?<Play/>:<Pause/>}</button></div><div className="drop-field">{drops.map(d=><button key={d.id} className={`drop drop-${d.kind}`} style={{left:`${d.x}%`,top:`${d.y}%`}} onClick={()=>pop(d.id)}>💧<span>+30</span></button>)}<div className="sparkle-field">✦ ✧ ✦ ✦ ✧ ✦ ✧ ✦</div></div>{time===0&&<div className="game-over"><strong>Beautiful! {score} points</strong><button className="pink-button" onClick={()=>{setScore(0);setTime(30);setDrops(newDrops())}}>Play Again</button></div>}</div>}
function newDrops(){return Array.from({length:6},(_,i)=>randomDrop(i))} function randomDrop(id){return{id,x:8+Math.random()*78,y:20+Math.random()*58,kind:id%5}}

function StashStackScreen({data,go,setGameScore}){const [height,setHeight]=useState(0),[best,setBest]=useState(data.gameScores.stashStack||0);const drop=()=>{const n=height+1;setHeight(n);if(n>best){setBest(n);setGameScore('stashStack',n)}if(data.settings.haptics&&navigator.vibrate)navigator.vibrate(16)};return <div className="screen night game-screen stack-screen"><ScreenHeader title="Stash Stack" go={()=>go('pump')} night action={<span className="coin">● {best}</span>}/><div className="stack-score"><span>Height</span><strong>{height}</strong><small>Best: {best}</small></div><div className="stack-scene"><div className="moon">☾</div><div className="falling-bottle">🍼</div><div className="stacked-milk" style={{height:`${Math.min(240,height*14)}px`}}>{Array.from({length:Math.min(height,12)},(_,i)=><span key={i}>▰</span>)}</div><div className="milk-bin"><strong>MILK</strong></div><div className="scale-base">✿</div></div><button className="tap-drop" onClick={drop}>Tap to Drop</button></div>}

const MATCH_ICONS=['🌸','⭐','💗','☁️','🌙','🍼','🍓','🐰']
function MamaMatchScreen({data,go,setGameScore}){const make=()=>shuffle([...MATCH_ICONS,...MATCH_ICONS]).map((icon,i)=>({id:i,icon,open:false,matched:false}));const [cards,setCards]=useState(make),[moves,setMoves]=useState(0),[seconds,setSeconds]=useState(0);const open=cards.filter(c=>c.open&&!c.matched),done=cards.every(c=>c.matched);useEffect(()=>{if(done)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[done]);useEffect(()=>{if(done&&seconds)setGameScore('mamaMatch',seconds)},[done]);const flip=id=>{if(open.length>=2)return;const next=cards.map(c=>c.id===id?{...c,open:true}:c);setCards(next);const opened=next.filter(c=>c.open&&!c.matched);if(opened.length===2){setMoves(m=>m+1);setTimeout(()=>setCards(cs=>{const [a,b]=cs.filter(c=>c.open&&!c.matched);if(!a||!b)return cs;return a.icon===b.icon?cs.map(c=>c.id===a.id||c.id===b.id?{...c,matched:true}:c):cs.map(c=>c.id===a.id||c.id===b.id?{...c,open:false}:c)}),500)}};const restart=()=>{setCards(make());setMoves(0);setSeconds(0)};return <div className="screen night game-screen match-screen"><ScreenHeader title="Mama Match" go={()=>go('pump')} night/><div className="match-hud"><strong>{toClock(seconds)}</strong><span>Moves<br/><b>{moves}</b></span></div><div className="match-grid">{cards.map(c=><button key={c.id} className={`match-card ${(c.open||c.matched)?'open':''}`} onClick={()=>flip(c.id)}>{(c.open||c.matched)?c.icon:'✿'}</button>)}</div>{done&&<div className="game-over"><strong>Matched in {seconds}s!</strong><button className="pink-button" onClick={restart}>Play Again</button></div>}</div>}

function SettingsScreen({data,go,setData,updateSettings,installPrompt}){const [goal,setGoal]=useState(data.settings.dailyGoal);const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='milky-mama-data.json';a.click();URL.revokeObjectURL(url)};return <div className="screen light"><ScreenHeader title="Settings" go={go}/><div className="settings-list"><SettingRow label="Daily Goal"><div className="inline-input"><input type="number" min="1" value={goal} onChange={e=>{const v=Number(e.target.value||24);setGoal(v);updateSettings({dailyGoal:v})}}/><span>oz</span></div></SettingRow><SettingRow label="Preferred Unit"><select value={data.settings.unit} onChange={e=>updateSettings({unit:e.target.value})}><option>oz</option><option>mL</option></select></SettingRow><SettingRow label="Haptics"><Switch checked={data.settings.haptics} onChange={v=>updateSettings({haptics:v})}/></SettingRow><SettingRow label="Sounds"><Switch checked={data.settings.sounds} onChange={v=>updateSettings({sounds:v})}/></SettingRow><SettingRow label="Reduce Motion"><Switch checked={data.settings.reduceMotion} onChange={v=>updateSettings({reduceMotion:v})}/></SettingRow><SettingRow label="Notifications"><span className="placeholder-text">Device settings</span></SettingRow></div><div className="settings-actions">{installPrompt&&<button onClick={()=>installPrompt.prompt()}><Download size={17}/> Install Milky Mama <ChevronRight/></button>}<button onClick={exportData}><Share2 size={17}/> Export Data (JSON) <ChevronRight/></button><button onClick={()=>setData(d=>({...d,gameScores:defaultData.gameScores}))}><RotateCcw size={17}/> Reset Game Scores <ChevronRight/></button><button onClick={()=>setData(d=>({...d,sessions:[]}))}><RotateCcw size={17}/> Reset Session History <ChevronRight/></button><button className="danger" onClick={()=>{if(confirm('Delete all Milky Mama data on this device?'))setData(defaultData)}}><Trash2 size={17}/> Delete All Data</button></div></div>}
function SettingRow({label,children}){return <div className="setting-row"><span>{label}</span>{children}</div>} function Switch({checked,onChange}){return <button className={`switch ${checked?'on':''}`} onClick={()=>onChange(!checked)}><span/></button>}

function toClock(sec){const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function relativeTime(date){const mins=Math.floor((Date.now()-date.getTime())/60000);if(mins<1)return'Just now';if(mins<60)return`${mins}m ago`;const h=Math.floor(mins/60);if(h<24)return`${h}h ${mins%60}m ago`;return`${Math.floor(h/24)}d ago`}
function sumLocation(stash,loc){return stash.filter(x=>x.location===loc).reduce((a,b)=>a+Number(b.ounces),0)}
function calcStreak(sessions){const days=[...new Set(sessions.map(s=>new Date(s.startedAt).toDateString()))];let streak=0,d=new Date();for(let i=0;i<365;i++){if(days.includes(d.toDateString()))streak++;else if(i>0)break;d.setDate(d.getDate()-1)}return streak}
function dailyBuckets(sessions,count){const arr=[];for(let i=count-1;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const next=new Date(d);next.setDate(next.getDate()+1);const value=sessions.filter(s=>{const x=new Date(s.startedAt);return x>=d&&x<next}).reduce((a,b)=>a+Number(b.ounces),0);arr.push({label:d.toLocaleDateString(undefined,{weekday:'narrow'}),value})}return arr}
function groupSessions(sessions){return sessions.reduce((acc,s)=>{const k=new Date(s.startedAt).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'});(acc[k]??=[]).push(s);return acc},{})}
function getAchievements(data){const count=data.sessions.length,total=data.sessions.reduce((a,b)=>a+Number(b.ounces),0),streak=calcStreak(data.sessions),stored=data.stash.reduce((a,b)=>a+Number(b.ounces),0);return[{id:'first',icon:'💧',title:'First Drop',desc:'Log your first session',unlocked:count>=1,progress:`${count}/1`},{id:'start',icon:'⭐',title:'Getting Started',desc:'Log 5 sessions',unlocked:count>=5,progress:`${Math.min(count,5)}/5`},{id:'track',icon:'🌸',title:'Keeping Track',desc:'Log 25 sessions',unlocked:count>=25,progress:`${Math.min(count,25)}/25`},{id:'routine',icon:'🌺',title:'Routine Builder',desc:'Reach a 3 day logging streak',unlocked:streak>=3,progress:`${Math.min(streak,3)}/3`},{id:'stash',icon:'🌿',title:'Stash Starter',desc:'Store 20 ounces',unlocked:stored>=20,progress:`${Math.min(Math.round(stored),20)}/20`},{id:'fifty',icon:'💗',title:'Fifty Ounces',desc:'Pump 50 ounces total',unlocked:total>=50,progress:`${Math.min(Math.round(total),50)}/50`}]}
function shuffle(a){return a.sort(()=>Math.random()-.5)}
