const STORAGE_KEY='milkyMama.v1'
const DEVICE_KEY='milkyMama.pushDeviceId'
const LAST_SYNC_KEY='milkyMama.pushLastSync'
const PUSH_URL='https://qgpjkmitexjvciftpkzh.supabase.co/functions/v1/push-reminders'
const VAPID_PUBLIC_KEY='BO6cOfVUDyGVGh7XRJvpoV7iKxLVjJUEfB6dPt9LrP6BR38zQoTVSeqjak058RExTPthY7dfTedeuyV0qhwQD9Q'
function b64(v){const p='='.repeat((4-v.length%4)%4),raw=atob((v+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function deviceId(){let v=localStorage.getItem(DEVICE_KEY);if(!v){v=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(DEVICE_KEY,v)}return v}
function state(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'),r=d.reminders||{};return{enabled:Boolean(r.enabled),mode:['times','smart'].includes(r.mode)?r.mode:'interval',intervalMinutes:Number(r.intervalMinutes||180),times:Array.isArray(r.times)?r.times:[],anchorAt:r.anchorAt||Date.now(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',schedule:{smart:r.smart||{},temporary:r.temporary||null}}}catch{return null}}
async function post(body){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const res=await fetch(PUSH_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal}),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`Push request failed: ${res.status}`);return data}finally{clearTimeout(t)}}
function standalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
function supportState(){if(!('serviceWorker'in navigator)||!('Notification'in window)||!('PushManager'in window))return{supported:false,reason:'Web Push is not available in this browser.'};if(!standalone())return{supported:false,reason:'Add Milky Mama to your iPhone Home Screen first, then open it from the Home Screen.'};return{supported:true,reason:''}}
async function requestPermission(){const s=supportState();if(!s.supported)throw new Error(s.reason);if(Notification.permission==='granted')return'granted';if(Notification.permission==='denied')throw new Error('Notifications are blocked. Allow Milky Mama notifications in iPhone Settings.');const result=await Notification.requestPermission();if(result!=='granted')throw new Error('Notification permission was not granted.');return result}
async function subscription(ask=false){const s=supportState();if(!s.supported)throw new Error(s.reason);if(ask)await requestPermission();if(Notification.permission!=='granted')return null;const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(VAPID_PUBLIC_KEY)});return sub}
async function sync(force=false,options={}){const r=state();if(!r)return;const fp=JSON.stringify(r);if(!force&&localStorage.getItem(LAST_SYNC_KEY)===fp)return;if(!r.enabled){await post({action:'disable',deviceId:deviceId()}).catch(()=>{});localStorage.setItem(LAST_SYNC_KEY,fp);return}const sub=await subscription(Boolean(options.askPermission));if(!sub)return;await post({action:'save',deviceId:deviceId(),subscription:sub.toJSON(),...r});localStorage.setItem(LAST_SYNC_KEY,fp)}
window.addEventListener('load',()=>{setTimeout(()=>sync(true).catch(()=>{}),1200);setInterval(()=>sync(false).catch(()=>{}),5000)})
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')sync(true).catch(()=>{})})
window.addEventListener('focus',()=>sync(true).catch(()=>{}))
window.MilkyMamaPush={sync:options=>sync(true,options),requestPermission,supported:()=>supportState().supported,supportState}
